# Stage 1: Dependency Resolution
# Using Alpine for minimal surface area
FROM node:24-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
# In a true airgapped pipeline, npm ci will hit your internal Nexus/Artifactory repository.
RUN npm ci

# Stage 2: Build Application
FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate the Next.js standalone bundle
RUN npm run build

# Stage 3: Production Runner (Airgapped Sandbox)
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3002
# Ensure Next.js binds to all network interfaces in the container
ENV HOSTNAME="0.0.0.0"

# Create non-root system users for security compliance
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy static assets
COPY --from=builder /app/public ./public

# Copy the standalone Next.js directory (only required node_modules for prod)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3002

# Server.js is generated by the Next.js standalone output configuration
CMD ["node", "server.js"]
